In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('hwdata.csv')
df.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

In [100]:
df_import=df[['neighbourhood_group','room_type','latitude','longitude','minimum_nights','price','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']]

In [101]:
df_import.head()

neighbourhood_group        room_type  latitude  longitude  minimum_nights  \
0            Brooklyn     Private room  40.64749  -73.97237               1   
1           Manhattan  Entire home/apt  40.75362  -73.98377               1   
2           Manhattan     Private room  40.80902  -73.94190               3   
3            Brooklyn  Entire home/apt  40.68514  -73.95976               1   
4           Manhattan  Entire home/apt  40.79851  -73.94399              10   

   price  number_of_reviews  reviews_per_month  \
0    149                  9               0.21   
1    225                 45               0.38   
2    150                  0                NaN   
3     89                270               4.64   
4     80                  9               0.10   

   calculated_host_listings_count  availability_365  
0                               6               365  
1                               2               355  
2                               1               365  
3                               1               194  
4                               1                 0

In [102]:
df_import.isnull().sum()

neighbourhood_group                   0
room_type                             0
latitude                              0
longitude                             0
minimum_nights                        0
price                                 0
number_of_reviews                     0
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [103]:
df_import.reviews_per_month=df_import.reviews_per_month.fillna(0)

C:\Users\jotei\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [104]:
df_import.isnull().sum()

neighbourhood_group               0
room_type                         0
latitude                          0
longitude                         0
minimum_nights                    0
price                             0
number_of_reviews                 0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

Question 1

In [105]:
df_import.neighbourhood_group.value_counts() #manhattan

Manhattan        21661
Brooklyn         20104
Queens            5666
Bronx             1091
Staten Island      373
Name: neighbourhood_group, dtype: int64

Split the data

In [107]:
from sklearn.model_selection import train_test_split
  

In [108]:
df_fulltrain,df_test=train_test_split(df_import,test_size=0.2,random_state=42)

In [109]:
df_train,df_val=train_test_split(df_fulltrain,test_size=0.25,random_state=42)

In [110]:
df_train.reset_index(drop=True)
df_test.reset_index(drop=True)
df_val.reset_index(drop=True)

neighbourhood_group        room_type  latitude  longitude  \
0               Brooklyn     Private room  40.70239  -73.92931   
1               Brooklyn  Entire home/apt  40.68498  -73.96618   
2               Brooklyn  Entire home/apt  40.66911  -73.94824   
3              Manhattan     Private room  40.79767  -73.96114   
4              Manhattan  Entire home/apt  40.76075  -73.99893   
5               Brooklyn  Entire home/apt  40.71120  -73.96566   
6              Manhattan  Entire home/apt  40.73243  -74.00932   
7              Manhattan  Entire home/apt  40.80630  -73.96268   
8              Manhattan      Shared room  40.77169  -73.99117   
9              Manhattan  Entire home/apt  40.80861  -73.94574   
10             Manhattan  Entire home/apt  40.80549  -73.96393   
11              Brooklyn     Private room  40.61964  -74.02518   
12              Brooklyn  Entire home/apt  40.62795  -73.96281   
13             Manhattan  Entire home/apt  40.77822  -73.98016   
14             Manhattan  Entire home/apt  40.79633  -73.94819   
15             Manhattan  Entire home/apt  40.84984  -73.94187   
16              Brooklyn  Entire home/apt  40.70000  -73.91714   
17             Manhattan     Private room  40.80031  -73.96775   
18              Brooklyn  Entire home/apt  40.65615  -73.91619   
19             Manhattan  Entire home/apt  40.77359  -73.94865   
20             Manhattan  Entire home/apt  40.77085  -73.94933   
21              Brooklyn  Entire home/apt  40.65944  -73.98898   
22              Brooklyn     Private room  40.68603  -73.87820   
23             Manhattan  Entire home/apt  40.78853  -73.97510   
24             Manhattan  Entire home/apt  40.73679  -73.98177   
25             Manhattan  Entire home/apt  40.76213  -73.94893   
26                Queens     Private room  40.74588  -73.83284   
27             Manhattan  Entire home/apt  40.73064  -73.99937   
28              Brooklyn  Entire home/apt  40.71760  -73.96148   
29              Brooklyn     Private room  40.65944  -73.91489   
...                  ...              ...       ...        ...   
9749           Manhattan  Entire home/apt  40.76413  -73.99301   
9750           Manhattan     Private room  40.72354  -73.99333   
9751           Manhattan     Private room  40.76256  -73.98935   
9752           Manhattan      Shared room  40.75722  -73.98162   
9753           Manhattan  Entire home/apt  40.75114  -73.99843   
9754           Manhattan  Entire home/apt  40.80622  -73.93875   
9755           Manhattan     Private room  40.72467  -73.98922   
9756            Brooklyn     Private room  40.70257  -73.98053   
9757           Manhattan     Private room  40.80464  -73.95637   
9758            Brooklyn  Entire home/apt  40.60245  -73.98140   
9759           Manhattan     Private room  40.77567  -73.97860   
9760            Brooklyn     Private room  40.69058  -73.93236   
9761           Manhattan  Entire home/apt  40.76574  -73.98018   
9762           Manhattan  Entire home/apt  40.75169  -73.97174   
9763           Manhattan  Entire home/apt  40.73525  -73.98074   
9764           Manhattan     Private room  40.71049  -74.00869   
9765           Manhattan     Private room  40.77158  -73.98976   
9766               Bronx     Private room  40.83754  -73.85764   
9767            Brooklyn     Private room  40.70790  -73.95598   
9768           Manhattan  Entire home/apt  40.80177  -73.95710   
9769            Brooklyn     Private room  40.71407  -73.93936   
9770           Manhattan  Entire home/apt  40.73833  -73.98943   
9771            Brooklyn  Entire home/apt  40.63178  -73.97128   
9772              Queens     Private room  40.71573  -73.76897   
9773           Manhattan     Private room  40.76201  -73.99876   
9774           Manhattan  Entire home/apt  40.75974  -73.98924   
9775               Bronx      Shared room  40.80952  -73.93005   
9776           Manhattan     Private room  40.73058  -73.98286   
9777            Brooklyn     Private room  40

In [111]:
y_train=df_train.price.values
y_test=df_test.price.values
y_val=df_val.price.values
y_train

array([ 99,  57,  70, ..., 299,  65,  92], dtype=int64)

In [112]:
del df_train['price']
del df_test['price']
del df_val['price']

Question 2

In [113]:
df_train.dtypes

neighbourhood_group                object
room_type                          object
latitude                          float64
longitude                         float64
minimum_nights                      int64
number_of_reviews                   int64
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [114]:
numerical=['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']
categorical=['neighbourhood_group','room_type']

In [115]:
df_train[numerical].corrwith(df_train.latitude )

latitude                          1.000000
longitude                         0.080301
minimum_nights                    0.027441
number_of_reviews                -0.006246
reviews_per_month                -0.007159
calculated_host_listings_count    0.019375
availability_365                 -0.005891
dtype: float64

In [116]:
print(df_train[numerical].corrwith(df_train.latitude))
print()
print(df_train[numerical].corrwith(df_train.longitude))
print()
print(df_train[numerical].corrwith(df_train.minimum_nights))
print()
print(df_train[numerical].corrwith(df_train.number_of_reviews))
print()
print(df_train[numerical].corrwith(df_train.reviews_per_month))
print()
print(df_train[numerical].corrwith(df_train.calculated_host_listings_count))
print()
print(df_train[numerical].corrwith(df_train.availability_365))

latitude                          1.000000
longitude                         0.080301
minimum_nights                    0.027441
number_of_reviews                -0.006246
reviews_per_month                -0.007159
calculated_host_listings_count    0.019375
availability_365                 -0.005891
dtype: float64

latitude                          0.080301
longitude                         1.000000
minimum_nights                   -0.060660
number_of_reviews                 0.055084
reviews_per_month                 0.134642
calculated_host_listings_count   -0.117041
availability_365                  0.083666
dtype: float64

latitude                          0.027441
longitude                        -0.060660
minimum_nights                    1.000000
number_of_reviews                -0.076020
reviews_per_month                -0.120703
calculated_host_listings_count    0.118647
availability_365                  0.138901
dtype: float64

latitude                         -0.006246
longit

Make price binary

In [118]:
above_average=np.zeros(len(y_train))
for i in range (len(y_train)):
    if y_train[i]>=152:
        above_average[i]=1
above_average

array([0., 0., 0., ..., 1., 0., 0.])

Question 3

In [119]:
from sklearn.metrics import mutual_info_score

In [121]:
def mutual_info_price_score(series):
    return mutual_info_score(series,above_average)
mi=df_train[categorical].apply(mutual_info_price_score)
mi

neighbourhood_group    0.046506
room_type              0.143226
dtype: float64

Question 4

In [122]:
#one hot enconding
from sklearn.feature_extraction import DictVectorizer
dicts=df_train[categorical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(dicts)
dv.transform(dicts)
dv.get_feature_names()

['neighbourhood_group=Bronx',
 'neighbourhood_group=Brooklyn',
 'neighbourhood_group=Manhattan',
 'neighbourhood_group=Queens',
 'neighbourhood_group=Staten Island',
 'room_type=Entire home/apt',
 'room_type=Private room',
 'room_type=Shared room']

In [123]:
train_dicts=df_train[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

['availability_365',
 'calculated_host_listings_count',
 'latitude',
 'longitude',
 'minimum_nights',
 'neighbourhood_group=Bronx',
 'neighbourhood_group=Brooklyn',
 'neighbourhood_group=Manhattan',
 'neighbourhood_group=Queens',
 'neighbourhood_group=Staten Island',
 'number_of_reviews',
 'reviews_per_month',
 'room_type=Entire home/apt',
 'room_type=Private room',
 'room_type=Shared room']

In [124]:
val_dicts=df_val[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val=dv.transform(val_dicts)

In [125]:
test_dicts=df_test[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(test_dicts)
X_test=dv.transform(test_dicts)

In [126]:
from sklearn.linear_model import LogisticRegression

In [127]:
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)

In [128]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=42, solver='lbfgs', tol=0.0001,
          verbose=0, warm_start=False)

In [129]:
w=model.coef_[0].round(3)
w0=model.intercept_[0]

In [130]:
y_pred=model.predict_proba(X_val)[:,1]

C:\Users\jotei\Anaconda3\lib\site-packages\sklearn\linear_model\base.py:340: RuntimeWarning: overflow encountered in exp
  np.exp(prob, prob)


In [133]:
y_pred

array([0.00012952, 0.00040934, 0.00033896, ..., 0.00015191, 0.00011644,
       0.00021736])

In [140]:
above_average=np.zeros(len(y_val))
for i in range (len(y_val)):
    if y_val[i]>=152:
        above_average[i]=1
above_average

array([0., 0., 1., ..., 0., 0., 0.])

In [141]:
abovepred=(y_pred>=0.5)

In [142]:
abovepred.astype(int)

array([0, 0, 0, ..., 0, 0, 0])

In [145]:
(above_average==abovepred.astype(int)).mean()

0.6934246855506698

Question 5

In [146]:
original_acc=0.6934246855506698

In [147]:
#model without neighbourhood_group

In [148]:
numerical=['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']
categorical=['room_type']

In [150]:
train_dicts=df_train[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

val_dicts=df_val[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val=dv.transform(val_dicts)

In [151]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict_proba(X_val)[:,1]
above_average=np.zeros(len(y_val))
abovepred=(y_pred>=0.5)
for i in range (len(y_val)):
    if y_val[i]>=152:
        above_average[i]=1
above_average
new_acc=(above_average==abovepred.astype(int)).mean()
print(original_acc-new_acc)

0.0


C:\Users\jotei\Anaconda3\lib\site-packages\sklearn\linear_model\base.py:340: RuntimeWarning: overflow encountered in exp
  np.exp(prob, prob)


In [153]:
# model without room_type
numerical=['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']
categorical=['neighbourhood_group']
train_dicts=df_train[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

val_dicts=df_val[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val=dv.transform(val_dicts)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict_proba(X_val)[:,1]
above_average=np.zeros(len(y_val))
abovepred=(y_pred>=0.5)
for i in range (len(y_val)):
    if y_val[i]>=152:
        above_average[i]=1
above_average
new_acc=(above_average==abovepred.astype(int)).mean()
print(original_acc-new_acc)

0.0


C:\Users\jotei\Anaconda3\lib\site-packages\sklearn\linear_model\base.py:340: RuntimeWarning: overflow encountered in exp
  np.exp(prob, prob)


In [154]:
#model without number of reviews
numerical=['latitude','longitude','minimum_nights','reviews_per_month','calculated_host_listings_count','availability_365']
categorical=['neighbourhood_group','room_type']
train_dicts=df_train[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

val_dicts=df_val[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val=dv.transform(val_dicts)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict_proba(X_val)[:,1]
above_average=np.zeros(len(y_val))
abovepred=(y_pred>=0.5)
for i in range (len(y_val)):
    if y_val[i]>=152:
        above_average[i]=1
above_average
new_acc=(above_average==abovepred.astype(int)).mean()
print(original_acc-new_acc)

KeyboardInterrupt: 

In [ ]:
#model without reviews per month
numerical=['latitude','longitude','minimum_nights','number_of_reviews','calculated_host_listings_count','availability_365']
categorical=['neighbourhood_group','room_type']
train_dicts=df_train[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

val_dicts=df_val[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val=dv.transform(val_dicts)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict_proba(X_val)[:,1]
above_average=np.zeros(len(y_val))
abovepred=(y_pred>=0.5)
for i in range (len(y_val)):
    if y_val[i]>=152:
        above_average[i]=1
above_average
new_acc=(above_average==abovepred.astype(int)).mean()
print(original_acc-new_acc)

Question 6

In [157]:
priceslog=np.log1p(df.price.values)

In [158]:
from sklearn.linear_model import Ridge

In [160]:
#alpha 1
numerical=['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']
categorical=['neighbourhood_group','room_type']
train_dicts=df_train[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

model = Ridge(alpha=1.0)
model.fit(X_train,y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [162]:
val_dicts=df_val[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val=dv.transform(val_dicts)

y_pred=model.predict(X_val)
y_pred


array([ 46.15171352, 244.28054473, 176.14668241, ..., 135.24308666,
        65.98427709, 203.78421508])

In [163]:
def rmse(y,y_pred):
    error=y-y_pred
    se=error**2
    mse=se.mean()
    return np.sqrt(mse)
rmse(y_val,y_pred)

211.9030691187127

In [164]:
#alpha 0
numerical=['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']
categorical=['neighbourhood_group','room_type']
train_dicts=df_train[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

model = Ridge(alpha=0)
model.fit(X_train,y_train)
val_dicts=df_val[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val=dv.transform(val_dicts)

y_pred=model.predict(X_val)

print(rmse(y_val,y_pred))


211.9022956825595


In [165]:
#alpha 0.01
numerical=['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']
categorical=['neighbourhood_group','room_type']
train_dicts=df_train[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

model = Ridge(alpha=0.01)
model.fit(X_train,y_train)
val_dicts=df_val[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val=dv.transform(val_dicts)

y_pred=model.predict(X_val)

print(rmse(y_val,y_pred))


211.9027328944188


In [166]:
#alpha 0.1
numerical=['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']
categorical=['neighbourhood_group','room_type']
train_dicts=df_train[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

model = Ridge(alpha=0.1)
model.fit(X_train,y_train)
val_dicts=df_val[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val=dv.transform(val_dicts)

y_pred=model.predict(X_val)

print(rmse(y_val,y_pred))


211.90268860605966


In [167]:
#alpha 10
numerical=['latitude','longitude','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']
categorical=['neighbourhood_group','room_type']
train_dicts=df_train[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

model = Ridge(alpha=10)
model.fit(X_train,y_train)
val_dicts=df_val[categorical + numerical].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val=dv.transform(val_dicts)

y_pred=model.predict(X_val)

print(rmse(y_val,y_pred))


211.94999657439922
